M48
; DRILL file {KiCad (6.0.10)} date Thu Feb 16 14:40:35 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-16T14:40:35-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.4Y-2.8
X5.4Y-2.9
X5.4Y-3.3
X5.4285Y-3.1617
X5.6Y-3.4
X5.9Y-3.2122
X6.0Y-3.1
X6.0Y-3.3
T2
X6.1Y-2.4
X6.1Y-2.6
T0
M30
